[canvas]
api_url = "https://canvas.instructure.com"
api_key = "YOUR_API_KEY"
course_id = 12345
lookback_time = 7

[canvas.grit_permission_quizzes]
"pg:Laser Cutter" = 440133

[canvas.grit_add_user_quizzes]
"3D Printers" = 440132

[canvas.quiz_id_to_group_id]
440133 = 93361

[grit]
api_url = "https://url.com"
api_key = "YOUR_API_KEY"
perform_upload = false

[misc]
backup_folder = "./backup"
